inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/bundle/**/*'
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ArgumentsForwarding:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/UnpackFirst:
  Enabled: false
