# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{image_size}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Keisuke Minami", "Ivan Kuchin"]
  s.date = %q{2011-02-21}
  s.description = %q{Measure following file dimensions: PCX, PSD, XPM, TIFF, XBM, PGM, PBM, PPM, BMP, JPEG, PNG, GIF, SWF}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".tmignore",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "image_size.gemspec",
    "lib/image_size.rb",
    "test/2-4-7.png",
    "test/4_1_2.gif",
    "test/bmp.bmp",
    "test/cursor.xbm",
    "test/detect.swf",
    "test/pbm.pbm",
    "test/pcx.pcx",
    "test/pgm.pgm",
    "test/test.xpm",
    "test/test_helper.rb",
    "test/test_image_size.rb",
    "test/tiff.tiff",
    "test/tokyo_tower.jpg",
    "test/tower_e.psd"
  ]
  s.homepage = %q{http://github.com/toy/image_size}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Measure image size using pure Ruby}
  s.test_files = [
    "test/test_helper.rb",
    "test/test_image_size.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rake-gem-ghost>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rake-gem-ghost>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rake-gem-ghost>, [">= 0"])
  end
end

